-- Seed exercise_library with full exercise data.
-- Safe to re-run: uses ON CONFLICT DO NOTHING.

INSERT INTO exercise_library (id, name, primary_muscle, secondary_muscles, movement_pattern, equipment, difficulty, instructions, form_cues, common_mistakes, youtube_search_url, alternatives)
VALUES
  -- CHEST
  ('barbell-bench-press', 'Barbell Bench Press', 'chest', ARRAY['triceps','shoulders'], 'push', ARRAY['barbell'], 'intermediate',
   'Lie on a flat bench with eyes under the bar. Grip slightly wider than shoulder-width. Unrack, lower the bar to mid-chest with elbows at ~45 degrees, then press up to lockout.',
   ARRAY['Retract and depress shoulder blades','Maintain slight arch in lower back','Drive feet into the floor','Bar path: slight diagonal from chest to over shoulders'],
   ARRAY['Flaring elbows to 90 degrees','Bouncing bar off chest','Lifting hips off the bench','Uneven lockout'],
   'https://www.youtube.com/results?search_query=how+to+barbell+bench+press+proper+form',
   ARRAY['dumbbell-bench-press','machine-chest-press','push-ups']),

  ('dumbbell-bench-press', 'Dumbbell Bench Press', 'chest', ARRAY['triceps','shoulders'], 'push', ARRAY['dumbbell'], 'beginner',
   'Sit on a flat bench with dumbbells on thighs. Kick them up as you lie back. Press dumbbells up until arms are extended, then lower to chest level with elbows at ~45 degrees.',
   ARRAY['Squeeze shoulder blades together throughout','Keep wrists neutral, not bent back','Lower until upper arms are parallel to floor','Press in a slight arc, dumbbells nearly touching at top'],
   ARRAY['Going too heavy and losing control','Flaring elbows wide','Not using full range of motion','Dropping dumbbells dangerously after set'],
   'https://www.youtube.com/results?search_query=how+to+dumbbell+bench+press+proper+form',
   ARRAY['barbell-bench-press','machine-chest-press','push-ups']),

  ('incline-dumbbell-press', 'Incline Dumbbell Press', 'chest', ARRAY['shoulders','triceps'], 'push', ARRAY['dumbbell'], 'intermediate',
   'Set bench to 30-45 degrees. Kick dumbbells up and press overhead. Lower with control until upper arms are parallel to the floor, then press back up.',
   ARRAY['Keep back flat against the bench','Bench angle 30-45 degrees, not higher','Elbows at 45-degree angle to torso','Full stretch at the bottom'],
   ARRAY['Setting bench too steep (becomes a shoulder press)','Arching excessively off the bench','Short range of motion','Uneven pressing'],
   'https://www.youtube.com/results?search_query=how+to+incline+dumbbell+press+proper+form',
   ARRAY['barbell-bench-press','machine-chest-press','cable-flyes']),

  ('machine-chest-press', 'Machine Chest Press', 'chest', ARRAY['triceps','shoulders'], 'push', ARRAY['machine'], 'beginner',
   'Adjust seat height so handles are at mid-chest. Grip handles, push forward until arms are extended but not locked, then return slowly.',
   ARRAY['Keep shoulder blades pinched back','Do not lock elbows at extension','Controlled tempo on the eccentric','Feet flat on the floor'],
   ARRAY['Seat too high or too low','Using momentum to push','Locking out elbows aggressively','Letting the weight stack slam'],
   'https://www.youtube.com/results?search_query=how+to+machine+chest+press+proper+form',
   ARRAY['barbell-bench-press','dumbbell-bench-press','push-ups']),

  ('cable-flyes', 'Cable Flyes', 'chest', ARRAY['shoulders'], 'isolation', ARRAY['cable'], 'intermediate',
   'Set cables at shoulder height. Step forward into a staggered stance. With a slight bend in the elbows, bring handles together in front of your chest in a hugging motion.',
   ARRAY['Maintain slight elbow bend throughout','Squeeze chest hard at the peak','Control the stretch on the way back','Keep torso stable, do not rotate'],
   ARRAY['Bending elbows too much (turns into a press)','Using too much weight and losing form','Leaning too far forward','Rushing the eccentric'],
   'https://www.youtube.com/results?search_query=how+to+cable+flyes+proper+form',
   ARRAY['dumbbell-flyes','dumbbell-bench-press','machine-chest-press']),

  ('push-ups', 'Push-ups', 'chest', ARRAY['triceps','shoulders','core'], 'push', ARRAY['bodyweight'], 'beginner',
   'Start in a high plank with hands slightly wider than shoulders. Lower your body until chest nearly touches the floor, keeping body in a straight line. Push back up.',
   ARRAY['Body in a straight line from head to heels','Elbows at 45 degrees, not flared','Full range of motion — chest to floor','Squeeze glutes to prevent hip sag'],
   ARRAY['Sagging hips','Flaring elbows to 90 degrees','Not going low enough','Leading with the chin instead of chest'],
   'https://www.youtube.com/results?search_query=how+to+push-ups+proper+form',
   ARRAY['dumbbell-bench-press','machine-chest-press','barbell-bench-press']),

  ('dumbbell-flyes', 'Dumbbell Flyes', 'chest', ARRAY['shoulders'], 'isolation', ARRAY['dumbbell'], 'intermediate',
   'Lie on a flat bench holding dumbbells above your chest with palms facing in. With a slight bend in elbows, lower the dumbbells in an arc until you feel a stretch. Return along the same arc.',
   ARRAY['Keep elbows slightly bent throughout','Feel the stretch at the bottom','Squeeze chest to bring dumbbells together','Controlled descent — do not drop arms'],
   ARRAY['Going too heavy','Straightening arms fully (stresses elbows)','Lowering too far past shoulder line','Turning it into a press by bending elbows deeply'],
   'https://www.youtube.com/results?search_query=how+to+dumbbell+flyes+proper+form',
   ARRAY['cable-flyes','machine-chest-press','push-ups']),

  -- BACK
  ('barbell-row', 'Barbell Row', 'back', ARRAY['biceps','shoulders','core'], 'pull', ARRAY['barbell'], 'intermediate',
   'Hinge at the hips with knees slightly bent, torso at ~45 degrees. Grip barbell slightly wider than shoulder-width. Pull the bar to your lower chest/upper abdomen, squeeze, then lower.',
   ARRAY['Keep back flat — no rounding','Initiate pull with elbows, not hands','Squeeze shoulder blades at the top','Torso angle stays constant throughout'],
   ARRAY['Rounding the lower back','Using momentum to swing the weight up','Standing too upright','Pulling to the wrong position (too low or high)'],
   'https://www.youtube.com/results?search_query=how+to+barbell+row+proper+form',
   ARRAY['dumbbell-row','cable-row','t-bar-row']),

  ('dumbbell-row', 'Dumbbell Row', 'back', ARRAY['biceps','shoulders'], 'pull', ARRAY['dumbbell'], 'beginner',
   'Place one knee and hand on a bench. Hold a dumbbell in the other hand with arm extended. Pull the dumbbell to your hip, squeezing the shoulder blade back, then lower.',
   ARRAY['Keep back flat and parallel to ground','Pull to hip, not to chest','Minimize torso rotation','Full stretch at the bottom'],
   ARRAY['Rotating the torso to heave the weight','Pulling to the armpit instead of hip','Shrugging the shoulder up','Using too much bicep, not enough back'],
   'https://www.youtube.com/results?search_query=how+to+dumbbell+row+proper+form',
   ARRAY['barbell-row','cable-row','t-bar-row']),

  ('lat-pulldown', 'Lat Pulldown', 'back', ARRAY['biceps','shoulders'], 'pull', ARRAY['cable'], 'beginner',
   'Sit at a lat pulldown machine with thighs secured under pads. Grip the bar wider than shoulder-width. Pull the bar to your upper chest while leaning back slightly, then return slowly.',
   ARRAY['Lean back slightly — about 15 degrees','Drive elbows down and back','Squeeze lats at the bottom','Full stretch at the top — let lats lengthen'],
   ARRAY['Pulling behind the neck (injury risk)','Leaning too far back','Using biceps instead of lats','Not getting full range of motion'],
   'https://www.youtube.com/results?search_query=how+to+lat+pulldown+proper+form',
   ARRAY['pull-ups','dumbbell-row','cable-row']),

  ('cable-row', 'Cable Row (Seated)', 'back', ARRAY['biceps','shoulders'], 'pull', ARRAY['cable'], 'beginner',
   'Sit at a cable row station with feet on the platform, knees slightly bent. Grip the handle, sit upright, and pull to your abdomen. Squeeze shoulder blades, then extend arms back.',
   ARRAY['Keep chest up and back straight','Pull to belly button level','Squeeze shoulder blades at peak contraction','Do not lean too far forward or back'],
   ARRAY['Excessive forward/backward rocking','Rounding the upper back','Shrugging shoulders up during the pull','Using momentum instead of muscle'],
   'https://www.youtube.com/results?search_query=how+to+seated+cable+row+proper+form',
   ARRAY['barbell-row','dumbbell-row','t-bar-row']),

  ('t-bar-row', 'T-Bar Row', 'back', ARRAY['biceps','shoulders','core'], 'pull', ARRAY['barbell'], 'intermediate',
   'Straddle the T-bar with feet shoulder-width apart. Hinge at the hips, grip the handles, and pull the weight to your chest. Squeeze, then lower with control.',
   ARRAY['Chest up, back flat','Drive elbows past the torso','Squeeze the back hard at the top','Keep knees slightly bent'],
   ARRAY['Rounding the back','Standing too upright','Jerking the weight up','Cutting range of motion short'],
   'https://www.youtube.com/results?search_query=how+to+t-bar+row+proper+form',
   ARRAY['barbell-row','dumbbell-row','cable-row']),

  ('pull-ups', 'Pull-ups / Assisted Pull-ups', 'back', ARRAY['biceps','shoulders','core'], 'pull', ARRAY['pull_up_bar'], 'advanced',
   'Hang from a pull-up bar with palms facing away, slightly wider than shoulders. Pull yourself up until chin clears the bar, then lower with control. Use an assisted machine or band if needed.',
   ARRAY['Initiate by depressing shoulder blades','Drive elbows down toward hips','Full dead hang at the bottom','Chin over bar at the top'],
   ARRAY['Kipping or swinging','Not achieving full range of motion','Shrugging shoulders to ears','Crossing legs and losing core tension'],
   'https://www.youtube.com/results?search_query=how+to+pull-ups+proper+form',
   ARRAY['lat-pulldown','dumbbell-row','cable-row']),

  ('face-pulls', 'Face Pulls', 'shoulders', ARRAY['back'], 'pull', ARRAY['cable'], 'beginner',
   'Set a cable with rope attachment at upper chest height. Pull the rope toward your face, separating the ends as you pull. Externally rotate so hands end up beside your ears.',
   ARRAY['High elbow position throughout','Separate the rope ends as you pull','Squeeze rear delts and external rotators','Do not lean back excessively'],
   ARRAY['Using too much weight','Pulling to the chest instead of face','Not externally rotating at the end','Leaning back to compensate'],
   'https://www.youtube.com/results?search_query=how+to+face+pulls+proper+form',
   ARRAY['reverse-flyes','cable-lateral-raises','dumbbell-row']),

  -- SHOULDERS
  ('overhead-press-dumbbell', 'Overhead Press (Dumbbell)', 'shoulders', ARRAY['triceps','core'], 'push', ARRAY['dumbbell'], 'intermediate',
   'Sit or stand with dumbbells at shoulder height, palms facing forward. Press the dumbbells overhead until arms are fully extended, then lower back to shoulders.',
   ARRAY['Brace core tightly','Press in a slight arc, not straight out','Full lockout overhead','Do not excessively arch the lower back'],
   ARRAY['Arching the back too much','Pressing forward instead of up','Not going through full range of motion','Using leg drive unintentionally'],
   'https://www.youtube.com/results?search_query=how+to+dumbbell+overhead+press+proper+form',
   ARRAY['machine-shoulder-press','lateral-raises','push-ups']),

  ('lateral-raises', 'Lateral Raises', 'shoulders', ARRAY[]::text[], 'isolation', ARRAY['dumbbell'], 'beginner',
   'Stand with dumbbells at your sides. Raise arms out to the sides until parallel with the floor, leading with the elbows. Lower with control.',
   ARRAY['Slight bend in elbows throughout','Lead with elbows, not hands','Raise to shoulder height, no higher','Controlled descent — no swinging'],
   ARRAY['Using too much weight and swinging','Shrugging the traps to lift','Raising above shoulder level','Thumbs pointing up (reduces delt activation)'],
   'https://www.youtube.com/results?search_query=how+to+lateral+raises+proper+form',
   ARRAY['cable-lateral-raises','machine-shoulder-press','overhead-press-dumbbell']),

  ('front-raises', 'Front Raises', 'shoulders', ARRAY['chest'], 'isolation', ARRAY['dumbbell'], 'beginner',
   'Stand holding dumbbells in front of your thighs. Raise one or both arms straight in front to shoulder height. Lower with control.',
   ARRAY['Keep a slight bend in the elbows','Raise to shoulder height only','Control the negative','Keep torso still — no swinging'],
   ARRAY['Swinging the weight up','Raising above shoulder level','Arching the back','Going too heavy'],
   'https://www.youtube.com/results?search_query=how+to+front+raises+proper+form',
   ARRAY['overhead-press-dumbbell','lateral-raises','cable-lateral-raises']),

  ('reverse-flyes', 'Reverse Flyes (Rear Delt)', 'shoulders', ARRAY['back'], 'isolation', ARRAY['dumbbell'], 'beginner',
   'Bend at the hips with back flat, dumbbells hanging below. Raise the dumbbells out to the sides, squeezing your rear delts. Lower slowly.',
   ARRAY['Keep torso angle constant','Slight elbow bend throughout','Squeeze shoulder blades together at top','Use light weight with strict form'],
   ARRAY['Using momentum to swing the weights','Standing too upright','Excessive elbow bending','Shrugging the traps'],
   'https://www.youtube.com/results?search_query=how+to+reverse+flyes+rear+delt+proper+form',
   ARRAY['face-pulls','cable-lateral-raises','dumbbell-row']),

  ('cable-lateral-raises', 'Cable Lateral Raises', 'shoulders', ARRAY[]::text[], 'isolation', ARRAY['cable'], 'beginner',
   'Stand sideways to a low cable pulley. Grab the handle with the far hand. Raise your arm out to the side until parallel to the floor, then lower with control.',
   ARRAY['Constant tension throughout the rep','Slight forward lean for better delt activation','Lead with the elbow','Controlled eccentric'],
   ARRAY['Turning it into a front raise','Shrugging the trap','Using body momentum','Not controlling the negative'],
   'https://www.youtube.com/results?search_query=how+to+cable+lateral+raises+proper+form',
   ARRAY['lateral-raises','overhead-press-dumbbell','machine-shoulder-press']),

  ('machine-shoulder-press', 'Machine Shoulder Press', 'shoulders', ARRAY['triceps'], 'push', ARRAY['machine'], 'beginner',
   'Adjust seat so handles are at shoulder height. Press handles overhead until arms are extended, then lower back to start.',
   ARRAY['Keep back flat against pad','Do not lock elbows at the top','Controlled tempo throughout','Breathe out on the press'],
   ARRAY['Seat too low (overloads shoulders at bad angle)','Locking elbows aggressively','Lifting butt off the seat','Using too much weight with partial reps'],
   'https://www.youtube.com/results?search_query=how+to+machine+shoulder+press+proper+form',
   ARRAY['overhead-press-dumbbell','lateral-raises','push-ups']),

  -- LEGS — QUADS
  ('barbell-squat', 'Barbell Squat', 'quads', ARRAY['glutes','hamstrings','core'], 'squat', ARRAY['barbell'], 'intermediate',
   'Set barbell on upper traps. Unrack and step back. Feet shoulder-width apart, toes slightly out. Squat down until thighs are at least parallel, then drive up through your heels.',
   ARRAY['Chest up throughout the movement','Knees track over toes','Hit parallel depth or below','Drive through the whole foot'],
   ARRAY['Knees caving inward','Leaning too far forward (good morning squat)','Not hitting depth','Rounding the lower back at the bottom'],
   'https://www.youtube.com/results?search_query=how+to+barbell+squat+proper+form',
   ARRAY['leg-press','goblet-squat','hack-squat']),

  ('leg-press', 'Leg Press', 'quads', ARRAY['glutes','hamstrings'], 'squat', ARRAY['machine'], 'beginner',
   'Sit in the leg press with feet shoulder-width on the platform. Release the safeties. Lower the platform by bending knees to ~90 degrees, then press back up.',
   ARRAY['Keep lower back pressed into the pad','Do not let knees cave inward','Do not lock knees at the top','Foot placement affects muscle emphasis'],
   ARRAY['Going too deep and rounding lower back','Locking out knees','Placing feet too high or low on the platform','Using too much weight with half reps'],
   'https://www.youtube.com/results?search_query=how+to+leg+press+proper+form',
   ARRAY['barbell-squat','goblet-squat','hack-squat']),

  ('goblet-squat', 'Goblet Squat', 'quads', ARRAY['glutes','core'], 'squat', ARRAY['dumbbell','kettlebell'], 'beginner',
   'Hold a dumbbell or kettlebell at chest height with both hands. Squat down keeping the weight close to your body, elbows inside the knees. Stand back up.',
   ARRAY['Keep the weight close to your chest','Elbows between knees at the bottom','Upright torso throughout','Full depth — hip crease below knee'],
   ARRAY['Leaning forward','Letting the weight drift away from the body','Not going deep enough','Knees caving inward'],
   'https://www.youtube.com/results?search_query=how+to+goblet+squat+proper+form',
   ARRAY['barbell-squat','leg-press','bulgarian-split-squat']),

  ('leg-extension', 'Leg Extension', 'quads', ARRAY[]::text[], 'isolation', ARRAY['machine'], 'beginner',
   'Sit in the machine with the pad on your shins just above the ankles. Extend your legs until straight, squeeze the quads, then lower slowly.',
   ARRAY['Squeeze the quads hard at full extension','Controlled eccentric — 2-3 seconds down','Keep back flat against the pad','Adjust pad to sit just above ankles'],
   ARRAY['Using momentum to swing the weight','Not achieving full extension','Going too heavy with partial reps','Lifting hips off the seat'],
   'https://www.youtube.com/results?search_query=how+to+leg+extension+proper+form',
   ARRAY['barbell-squat','leg-press','goblet-squat']),

  ('bulgarian-split-squat', 'Bulgarian Split Squat', 'quads', ARRAY['glutes','hamstrings'], 'squat', ARRAY['dumbbell'], 'intermediate',
   'Stand with one foot forward and the rear foot elevated on a bench behind you. Hold dumbbells at your sides. Lower until the front thigh is parallel to the floor, then drive up.',
   ARRAY['Most weight on the front leg','Front knee tracks over the toes','Upright torso','Control the descent — do not drop'],
   ARRAY['Front foot too close to the bench','Leaning too far forward','Rear foot doing too much work','Knee collapsing inward'],
   'https://www.youtube.com/results?search_query=how+to+bulgarian+split+squat+proper+form',
   ARRAY['barbell-squat','goblet-squat','leg-press']),

  ('hack-squat', 'Hack Squat', 'quads', ARRAY['glutes','hamstrings'], 'squat', ARRAY['machine'], 'intermediate',
   'Stand in the hack squat machine with back against the pad, shoulders under the pads. Feet shoulder-width on the platform. Lower until thighs are parallel, then press back up.',
   ARRAY['Keep back flat against the pad','Knees track over toes','Full range of motion','Do not lock knees at the top'],
   ARRAY['Cutting depth short','Placing feet too far forward or back','Locking knees at extension','Letting knees cave inward'],
   'https://www.youtube.com/results?search_query=how+to+hack+squat+proper+form',
   ARRAY['barbell-squat','leg-press','goblet-squat']),

  -- LEGS — HAMSTRINGS / GLUTES
  ('romanian-deadlift', 'Romanian Deadlift', 'hamstrings', ARRAY['glutes','back','core'], 'hinge', ARRAY['barbell','dumbbell'], 'intermediate',
   'Hold a barbell at hip height. Push hips back while keeping a slight knee bend, lowering the bar along your legs until you feel a deep hamstring stretch. Drive hips forward to stand.',
   ARRAY['Hips go BACK, not down','Bar stays close to the legs','Slight knee bend — this is not a squat','Feel the stretch in the hamstrings'],
   ARRAY['Rounding the lower back','Bending the knees too much','Bar drifting away from the body','Not hinging enough at the hips'],
   'https://www.youtube.com/results?search_query=how+to+romanian+deadlift+proper+form',
   ARRAY['leg-curl','hip-thrust','good-mornings']),

  ('leg-curl', 'Leg Curl (Machine)', 'hamstrings', ARRAY[]::text[], 'isolation', ARRAY['machine'], 'beginner',
   'Lie face down on the leg curl machine. Adjust the pad to sit just above your ankles. Curl the weight up by bending your knees, squeeze at the top, then lower slowly.',
   ARRAY['Keep hips pressed into the pad','Full range of motion','Squeeze hamstrings at peak contraction','Controlled eccentric — 2-3 seconds'],
   ARRAY['Lifting hips off the pad','Using momentum to swing the weight','Not achieving full contraction','Going too heavy with partial reps'],
   'https://www.youtube.com/results?search_query=how+to+leg+curl+machine+proper+form',
   ARRAY['romanian-deadlift','good-mornings','cable-pull-through']),

  ('hip-thrust', 'Hip Thrust (Barbell)', 'glutes', ARRAY['hamstrings','core'], 'hinge', ARRAY['barbell'], 'intermediate',
   'Sit on the floor with upper back against a bench, barbell over your hips (use a pad). Plant feet flat, drive hips up until your body forms a straight line from shoulders to knees. Squeeze glutes at the top.',
   ARRAY['Drive through heels','Squeeze glutes hard at the top','Chin tucked — do not hyperextend the neck','Knees at 90 degrees at the top'],
   ARRAY['Hyperextending the lower back at the top','Feet too far forward or too close','Not achieving full hip extension','Pushing through toes instead of heels'],
   'https://www.youtube.com/results?search_query=how+to+barbell+hip+thrust+proper+form',
   ARRAY['glute-bridge','cable-pull-through','romanian-deadlift']),

  ('glute-bridge', 'Glute Bridge', 'glutes', ARRAY['hamstrings','core'], 'hinge', ARRAY['bodyweight','dumbbell'], 'beginner',
   'Lie on your back with knees bent and feet flat on the floor. Push hips up by squeezing glutes until body forms a straight line from shoulders to knees. Lower with control.',
   ARRAY['Squeeze glutes at the top — hold for 1 second','Drive through heels','Keep core braced','Do not hyperextend at the top'],
   ARRAY['Pushing through lower back instead of glutes','Not squeezing at the top','Feet too close or too far from hips','Rushing through reps'],
   'https://www.youtube.com/results?search_query=how+to+glute+bridge+proper+form',
   ARRAY['hip-thrust','banded-glute-bridge','cable-pull-through']),

  ('cable-pull-through', 'Cable Pull-through', 'glutes', ARRAY['hamstrings','core'], 'hinge', ARRAY['cable'], 'beginner',
   'Face away from a low cable with rope between your legs. Hinge at the hips, letting the cable pull you back, then drive hips forward explosively to stand tall.',
   ARRAY['This is a hip hinge — not a squat','Arms stay straight throughout','Squeeze glutes hard at the top','Soft knees, do not bend them more as you hinge'],
   ARRAY['Squatting instead of hinging','Pulling with the arms','Not driving hips through fully','Rounding the lower back'],
   'https://www.youtube.com/results?search_query=how+to+cable+pull+through+proper+form',
   ARRAY['romanian-deadlift','hip-thrust','good-mornings']),

  ('good-mornings', 'Good Mornings', 'hamstrings', ARRAY['glutes','back','core'], 'hinge', ARRAY['barbell'], 'intermediate',
   'Place a barbell on your upper back. With a slight knee bend, hinge at the hips and lower your torso until it is nearly parallel to the floor. Return to standing by driving hips forward.',
   ARRAY['Keep back straight throughout','Hinge at the hips, not the waist','Feel the hamstring stretch','Use lighter weight until form is solid'],
   ARRAY['Rounding the back','Bending the knees too much','Going too heavy too soon','Not achieving full hip hinge'],
   'https://www.youtube.com/results?search_query=how+to+good+mornings+exercise+proper+form',
   ARRAY['romanian-deadlift','leg-curl','cable-pull-through']),

  -- ARMS
  ('barbell-curl', 'Barbell Curl', 'biceps', ARRAY['forearms'], 'isolation', ARRAY['barbell'], 'beginner',
   'Stand holding a barbell with an underhand grip, arms fully extended. Curl the bar up to shoulder height by bending at the elbows. Lower slowly.',
   ARRAY['Keep elbows pinned to your sides','Squeeze biceps at the top','Full extension at the bottom','Controlled eccentric'],
   ARRAY['Swinging the body to cheat','Elbows drifting forward','Not using full range of motion','Going too heavy with poor form'],
   'https://www.youtube.com/results?search_query=how+to+barbell+curl+proper+form',
   ARRAY['dumbbell-curl','hammer-curl','cable-row']),

  ('dumbbell-curl', 'Dumbbell Curl', 'biceps', ARRAY['forearms'], 'isolation', ARRAY['dumbbell'], 'beginner',
   'Stand or sit holding dumbbells at your sides with palms facing forward. Curl both dumbbells up to shoulder height, squeeze, then lower. Can be done alternating.',
   ARRAY['Keep elbows stationary at your sides','Supinate (turn palms up) as you curl','Squeeze at the top for a moment','Lower under control'],
   ARRAY['Swinging the weight','Elbows moving forward and back','Half reps — not extending fully','Leaning back to lift heavier'],
   'https://www.youtube.com/results?search_query=how+to+dumbbell+curl+proper+form',
   ARRAY['barbell-curl','hammer-curl','lat-pulldown']),

  ('hammer-curl', 'Hammer Curl', 'biceps', ARRAY['forearms'], 'isolation', ARRAY['dumbbell'], 'beginner',
   'Stand holding dumbbells with a neutral grip (palms facing each other). Curl the dumbbells up to shoulder height while keeping the neutral grip. Lower slowly.',
   ARRAY['Palms face each other throughout','Elbows stay at your sides','Squeeze at the top','Do not swing'],
   ARRAY['Turning it into a regular curl by rotating wrists','Swinging the body','Elbows drifting forward','Partial range of motion'],
   'https://www.youtube.com/results?search_query=how+to+hammer+curl+proper+form',
   ARRAY['barbell-curl','dumbbell-curl','lat-pulldown']),

  ('tricep-pushdown', 'Tricep Pushdown (Cable)', 'triceps', ARRAY[]::text[], 'isolation', ARRAY['cable'], 'beginner',
   'Stand at a cable machine with a straight bar or rope at head height. Push the attachment down by extending your elbows until arms are fully straight. Return slowly.',
   ARRAY['Keep elbows pinned to your sides','Squeeze triceps at full extension','Controlled eccentric — do not let the weight yank your arms up','Slight forward lean for stability'],
   ARRAY['Elbows flaring or moving forward','Using shoulders to press down','Not achieving full extension','Letting the weight stack slam'],
   'https://www.youtube.com/results?search_query=how+to+tricep+pushdown+cable+proper+form',
   ARRAY['overhead-tricep-extension','skull-crushers','push-ups']),

  ('overhead-tricep-extension', 'Overhead Tricep Extension', 'triceps', ARRAY[]::text[], 'isolation', ARRAY['dumbbell','cable'], 'beginner',
   'Hold a dumbbell overhead with both hands. Lower it behind your head by bending at the elbows, keeping upper arms vertical. Extend back to the starting position.',
   ARRAY['Keep upper arms close to your head','Full stretch at the bottom','Squeeze triceps at the top','Core engaged to prevent arching'],
   ARRAY['Elbows flaring outward','Arching the lower back','Not going through full range of motion','Using too much weight'],
   'https://www.youtube.com/results?search_query=how+to+overhead+tricep+extension+proper+form',
   ARRAY['tricep-pushdown','skull-crushers','push-ups']),

  ('skull-crushers', 'Skull Crushers', 'triceps', ARRAY[]::text[], 'isolation', ARRAY['barbell','dumbbell'], 'intermediate',
   'Lie on a flat bench holding a barbell or dumbbells with arms extended over your chest. Lower the weight toward your forehead by bending at the elbows. Extend back up.',
   ARRAY['Upper arms stay vertical — only forearms move','Lower to forehead or just behind the head','Controlled descent','Squeeze triceps at the top'],
   ARRAY['Elbows flaring outward','Dropping the weight too fast','Upper arms swaying back and forth','Using too much weight'],
   'https://www.youtube.com/results?search_query=how+to+skull+crushers+proper+form',
   ARRAY['tricep-pushdown','overhead-tricep-extension','push-ups']),

  -- CORE
  ('dead-bug', 'Dead Bug', 'core', ARRAY[]::text[], 'isolation', ARRAY['bodyweight'], 'beginner',
   'Lie on your back with arms extended toward the ceiling and knees bent at 90 degrees. Slowly extend one arm overhead and the opposite leg outward. Return and alternate.',
   ARRAY['Press lower back flat into the floor throughout','Move slowly and with control','Breathe out as you extend','Keep non-moving limbs stable'],
   ARRAY['Lower back arching off the floor','Moving too quickly','Not coordinating opposite arm/leg','Holding breath'],
   'https://www.youtube.com/results?search_query=how+to+dead+bug+exercise+proper+form',
   ARRAY['plank','bird-dog','hanging-leg-raise']),

  ('plank', 'Plank', 'core', ARRAY['shoulders'], 'isolation', ARRAY['bodyweight'], 'beginner',
   'Start in a forearm plank position: elbows under shoulders, body in a straight line from head to heels. Hold the position, bracing your core.',
   ARRAY['Straight line from head to heels','Squeeze glutes and quads','Do not let hips sag or pike up','Breathe normally throughout'],
   ARRAY['Hips sagging toward the floor','Hips piking up too high','Looking forward (strains neck)','Holding breath'],
   'https://www.youtube.com/results?search_query=how+to+plank+exercise+proper+form',
   ARRAY['side-plank','dead-bug','bird-dog']),

  ('side-plank', 'Side Plank', 'core', ARRAY['shoulders'], 'isolation', ARRAY['bodyweight'], 'beginner',
   'Lie on your side with elbow under shoulder and feet stacked. Lift hips off the ground to form a straight line. Hold.',
   ARRAY['Hips stacked — do not rotate forward','Straight line from head to feet','Elbow directly under shoulder','Breathe normally'],
   ARRAY['Hips dropping','Rotating forward or backward','Elbow too far from shoulder','Holding breath'],
   'https://www.youtube.com/results?search_query=how+to+side+plank+proper+form',
   ARRAY['plank','cable-woodchop','dead-bug']),

  ('cable-woodchop', 'Cable Woodchop', 'core', ARRAY['shoulders'], 'isolation', ARRAY['cable'], 'intermediate',
   'Set a cable at the highest position. Stand sideways, grab the handle with both hands. Pull diagonally down and across your body, rotating your torso. Control back to start.',
   ARRAY['Rotate through the core, not just the arms','Keep arms relatively straight','Control the return — do not let it snap back','Pivot on the back foot'],
   ARRAY['Using only the arms','Not controlling the eccentric','Rounding the back','Standing too close to the cable'],
   'https://www.youtube.com/results?search_query=how+to+cable+woodchop+proper+form',
   ARRAY['side-plank','hanging-leg-raise','dead-bug']),

  ('hanging-leg-raise', 'Hanging Leg Raise', 'core', ARRAY[]::text[], 'isolation', ARRAY['pull_up_bar'], 'advanced',
   'Hang from a pull-up bar with arms extended. Raise your legs in front of you until parallel to the floor (or higher). Lower with control.',
   ARRAY['Minimize swinging','Curl pelvis up — do not just lift legs','Controlled descent','Keep legs as straight as possible'],
   ARRAY['Swinging to generate momentum','Only lifting legs without pelvic tilt','Dropping legs on the way down','Bending knees excessively'],
   'https://www.youtube.com/results?search_query=how+to+hanging+leg+raise+proper+form',
   ARRAY['dead-bug','plank','ab-wheel-rollout']),

  ('ab-wheel-rollout', 'Ab Wheel Rollout', 'core', ARRAY['shoulders'], 'isolation', ARRAY['ab_wheel'], 'intermediate',
   'Kneel on the floor holding an ab wheel. Roll forward, extending your body as far as you can while keeping your core tight. Pull back to the starting position.',
   ARRAY['Brace core — do not let lower back sag','Tuck pelvis slightly','Only go as far as you can control','Squeeze abs to pull back'],
   ARRAY['Letting the lower back collapse','Going too far before building strength','Leading with the hips on the return','Not engaging the core throughout'],
   'https://www.youtube.com/results?search_query=how+to+ab+wheel+rollout+proper+form',
   ARRAY['plank','dead-bug','hanging-leg-raise']),

  ('bird-dog', 'Bird Dog', 'core', ARRAY['glutes'], 'isolation', ARRAY['bodyweight'], 'beginner',
   'Start on all fours. Extend one arm forward and the opposite leg back, forming a straight line. Hold briefly, then return. Alternate sides.',
   ARRAY['Keep hips level — no rotation','Extend fully through fingertips and heel','Move slowly and deliberately','Brace core throughout'],
   ARRAY['Rotating hips to one side','Arching the lower back','Rushing through reps','Not extending fully'],
   'https://www.youtube.com/results?search_query=how+to+bird+dog+exercise+proper+form',
   ARRAY['dead-bug','plank','side-plank']),

  -- GLUTE ACTIVATION (Warm-up)
  ('clamshell', 'Clamshell', 'glutes', ARRAY[]::text[], 'isolation', ARRAY['band','bodyweight'], 'beginner',
   'Lie on your side with knees bent at 45 degrees and feet together. Open the top knee like a clamshell while keeping feet touching. Lower with control.',
   ARRAY['Keep feet together throughout','Do not rotate the pelvis backward','Squeeze the glute at the top','Controlled tempo'],
   ARRAY['Rolling the hips back to cheat','Moving too fast','Not squeezing at the top','Feet separating'],
   'https://www.youtube.com/results?search_query=how+to+clamshell+exercise+proper+form',
   ARRAY['banded-glute-bridge','fire-hydrant','donkey-kick']),

  ('banded-glute-bridge', 'Banded Glute Bridge', 'glutes', ARRAY['hamstrings'], 'hinge', ARRAY['band'], 'beginner',
   'Place a resistance band just above your knees. Lie on your back with knees bent. Drive hips up while pressing knees outward against the band. Squeeze at the top, lower slowly.',
   ARRAY['Press knees outward against the band throughout','Squeeze glutes hard at the top','Drive through heels','Keep core braced'],
   ARRAY['Letting knees cave in','Pushing through toes','Not squeezing at the top','Arching lower back instead of driving hips'],
   'https://www.youtube.com/results?search_query=how+to+banded+glute+bridge+proper+form',
   ARRAY['glute-bridge','clamshell','fire-hydrant']),

  ('fire-hydrant', 'Fire Hydrant', 'glutes', ARRAY[]::text[], 'isolation', ARRAY['bodyweight','band'], 'beginner',
   'Start on all fours. Keeping the knee bent at 90 degrees, lift one leg out to the side until the thigh is parallel to the floor. Lower with control.',
   ARRAY['Keep hips level — do not shift weight','Lift with the glute, not the hip flexor','Keep core engaged','Controlled movement throughout'],
   ARRAY['Shifting the entire body to one side','Rotating the hips open','Moving too quickly','Arching the back'],
   'https://www.youtube.com/results?search_query=how+to+fire+hydrant+exercise+proper+form',
   ARRAY['clamshell','donkey-kick','banded-glute-bridge']),

  ('donkey-kick', 'Donkey Kick', 'glutes', ARRAY['hamstrings'], 'isolation', ARRAY['bodyweight','band'], 'beginner',
   'Start on all fours. Keeping the knee bent at 90 degrees, drive one foot up toward the ceiling until the thigh is in line with the torso. Lower with control.',
   ARRAY['Keep the knee bent at 90 degrees throughout','Squeeze the glute at the top','Do not arch the lower back','Keep core tight and hips level'],
   ARRAY['Arching the lower back to get the leg higher','Using momentum instead of glute contraction','Rotating the hips','Not squeezing at the top'],
   'https://www.youtube.com/results?search_query=how+to+donkey+kick+exercise+proper+form',
   ARRAY['fire-hydrant','clamshell','banded-glute-bridge']),

  -- CARDIO
  ('treadmill-walk-incline', 'Treadmill Walk (Incline)', 'cardio', ARRAY['glutes','calves'], 'carry', ARRAY['treadmill'], 'beginner',
   'Set the treadmill to an incline of 8-15%. Walk at a moderate pace (5-6 km/h). Keep an upright posture and do not hold the handrails.',
   ARRAY['Upright posture — do not lean on handles','Swing arms naturally','Push through the whole foot','Maintain a brisk but conversational pace'],
   ARRAY['Holding the handrails (reduces calorie burn significantly)','Leaning forward into the belt','Setting speed too high for the incline','Slouching or looking down at phone'],
   'https://www.youtube.com/results?search_query=how+to+incline+treadmill+walk+proper+form',
   ARRAY['stationary-bike','elliptical','swimming']),

  ('stationary-bike', 'Stationary Bike', 'cardio', ARRAY['quads','hamstrings'], 'carry', ARRAY['stationary_bike'], 'beginner',
   'Adjust the seat so your knee has a slight bend at the bottom of the pedal stroke. Pedal at a steady cadence. Adjust resistance to maintain the desired heart rate zone.',
   ARRAY['Seat height: slight knee bend at bottom','Keep upper body relaxed, not hunched','Pedal through full circles, not just pushing down','Maintain steady cadence (60-90 RPM)'],
   ARRAY['Seat too low or too high','Gripping handlebars too tightly','Bouncing in the saddle (resistance too low)','Hunching shoulders'],
   'https://www.youtube.com/results?search_query=how+to+stationary+bike+workout+proper+form',
   ARRAY['treadmill-walk-incline','elliptical','swimming']),

  ('elliptical', 'Elliptical', 'cardio', ARRAY['quads','glutes'], 'carry', ARRAY['elliptical'], 'beginner',
   'Step onto the elliptical and grip the moving handles. Pedal in a smooth, circular motion while pushing and pulling the handles. Adjust resistance as needed.',
   ARRAY['Stand upright — do not lean on the console','Push through the heels, not the toes','Use both arms and legs','Keep a smooth, steady rhythm'],
   ARRAY['Leaning on the machine','Only using the legs (ignoring handles)','Setting resistance too low','Choppy, uneven strides'],
   'https://www.youtube.com/results?search_query=how+to+elliptical+workout+proper+form',
   ARRAY['treadmill-walk-incline','stationary-bike','swimming']),

  ('swimming', 'Swimming', 'cardio', ARRAY['back','shoulders','core'], 'carry', ARRAY[]::text[], 'intermediate',
   'Swim laps using any stroke (freestyle is most common). Focus on breathing rhythm and consistent stroke technique. Start with shorter intervals and build up.',
   ARRAY['Exhale underwater, inhale to the side','Keep body streamlined','Rotate the torso with each stroke','Kick from the hips, not the knees'],
   ARRAY['Holding breath instead of exhaling underwater','Lifting head too high to breathe','Kicking from the knees','Crossing over with the hand entry'],
   'https://www.youtube.com/results?search_query=how+to+swimming+freestyle+technique+proper+form',
   ARRAY['treadmill-walk-incline','stationary-bike','elliptical']),

  ('badminton', 'Badminton', 'cardio', ARRAY['shoulders','quads','core'], 'carry', ARRAY[]::text[], 'beginner',
   'Play singles or doubles badminton. Focus on quick footwork, proper grip, and explosive movements. Great for HIIT-style cardio with natural intervals.',
   ARRAY['Stay on the balls of your feet','Return to base position after each shot','Use wrist snap for power, not full arm','Keep racket up between shots'],
   ARRAY['Flat-footed stance','Not returning to center court','Using arm strength instead of wrist technique','Gripping the racket too tightly'],
   'https://www.youtube.com/results?search_query=how+to+badminton+basics+proper+form',
   ARRAY['swimming','treadmill-walk-incline','stationary-bike'])

ON CONFLICT (id) DO NOTHING;
