export type FoodCategory =
  | 'dal'
  | 'sabzi'
  | 'roti_rice'
  | 'protein'
  | 'breakfast'
  | 'fruits_snacks'
  | 'drinks'

export interface Food {
  id: string
  name: string
  aliases: string[]
  category: FoodCategory
  is_vegetarian: boolean
  serving_size: string
  serving_grams: number
  calories: number
  protein_g: number
  carbs_g: number
  fat_g: number
  fiber_g: number
  source: 'ifct-approximate' | 'manual' | 'estimated'
}

export const FOODS: Food[] = [
  // ─── DAL / LENTILS (per bowl ~200ml cooked) ─────────────
  {
    id: 'toor-dal',
    name: 'Toor Dal',
    aliases: ['arhar dal', 'pigeon pea dal'],
    category: 'dal',
    is_vegetarian: true,
    serving_size: '1 bowl (200ml)',
    serving_grams: 200,
    calories: 150,
    protein_g: 10,
    carbs_g: 24,
    fat_g: 1,
    fiber_g: 5,
    source: 'ifct-approximate',
  },
  {
    id: 'moong-dal',
    name: 'Moong Dal',
    aliases: ['green gram dal', 'yellow moong'],
    category: 'dal',
    is_vegetarian: true,
    serving_size: '1 bowl (200ml)',
    serving_grams: 200,
    calories: 140,
    protein_g: 11,
    carbs_g: 22,
    fat_g: 1,
    fiber_g: 4,
    source: 'ifct-approximate',
  },
  {
    id: 'chana-dal',
    name: 'Chana Dal',
    aliases: ['bengal gram dal', 'split chickpea'],
    category: 'dal',
    is_vegetarian: true,
    serving_size: '1 bowl (200ml)',
    serving_grams: 200,
    calories: 170,
    protein_g: 11,
    carbs_g: 26,
    fat_g: 2,
    fiber_g: 5,
    source: 'ifct-approximate',
  },
  {
    id: 'masoor-dal',
    name: 'Masoor Dal',
    aliases: ['red lentil dal'],
    category: 'dal',
    is_vegetarian: true,
    serving_size: '1 bowl (200ml)',
    serving_grams: 200,
    calories: 145,
    protein_g: 10,
    carbs_g: 23,
    fat_g: 1,
    fiber_g: 4,
    source: 'ifct-approximate',
  },
  {
    id: 'rajma',
    name: 'Rajma',
    aliases: ['kidney beans', 'rajma masala'],
    category: 'dal',
    is_vegetarian: true,
    serving_size: '1 bowl (200ml)',
    serving_grams: 200,
    calories: 180,
    protein_g: 9,
    carbs_g: 30,
    fat_g: 1,
    fiber_g: 6,
    source: 'ifct-approximate',
  },
  {
    id: 'chole',
    name: 'Chole / Chana Masala',
    aliases: ['chickpea curry', 'chole masala', 'chana'],
    category: 'dal',
    is_vegetarian: true,
    serving_size: '1 bowl (200ml)',
    serving_grams: 200,
    calories: 200,
    protein_g: 9,
    carbs_g: 30,
    fat_g: 5,
    fiber_g: 6,
    source: 'ifct-approximate',
  },
  {
    id: 'dal-makhani',
    name: 'Dal Makhani',
    aliases: ['maa ki dal', 'black dal'],
    category: 'dal',
    is_vegetarian: true,
    serving_size: '1 bowl (200ml)',
    serving_grams: 200,
    calories: 220,
    protein_g: 8,
    carbs_g: 25,
    fat_g: 9,
    fiber_g: 5,
    source: 'ifct-approximate',
  },

  // ─── SABZI / VEGETABLES (per bowl ~150g cooked) ─────────
  {
    id: 'aloo-gobi',
    name: 'Aloo Gobi',
    aliases: ['potato cauliflower', 'gobi aloo'],
    category: 'sabzi',
    is_vegetarian: true,
    serving_size: '1 bowl (150g)',
    serving_grams: 150,
    calories: 130,
    protein_g: 3,
    carbs_g: 18,
    fat_g: 5,
    fiber_g: 3,
    source: 'ifct-approximate',
  },
  {
    id: 'palak-paneer',
    name: 'Palak Paneer',
    aliases: ['spinach paneer', 'saag paneer'],
    category: 'sabzi',
    is_vegetarian: true,
    serving_size: '1 bowl (150g)',
    serving_grams: 150,
    calories: 200,
    protein_g: 11,
    carbs_g: 8,
    fat_g: 14,
    fiber_g: 2,
    source: 'ifct-approximate',
  },
  {
    id: 'paneer-bhurji',
    name: 'Paneer Bhurji',
    aliases: ['scrambled paneer'],
    category: 'sabzi',
    is_vegetarian: true,
    serving_size: '1 bowl (150g)',
    serving_grams: 150,
    calories: 250,
    protein_g: 14,
    carbs_g: 6,
    fat_g: 18,
    fiber_g: 1,
    source: 'ifct-approximate',
  },
  {
    id: 'mixed-veg-sabzi',
    name: 'Mixed Veg Sabzi',
    aliases: ['mix veg', 'mixed vegetable'],
    category: 'sabzi',
    is_vegetarian: true,
    serving_size: '1 bowl (150g)',
    serving_grams: 150,
    calories: 90,
    protein_g: 3,
    carbs_g: 12,
    fat_g: 4,
    fiber_g: 3,
    source: 'ifct-approximate',
  },
  {
    id: 'bhindi-masala',
    name: 'Bhindi Masala',
    aliases: ['okra', 'lady finger'],
    category: 'sabzi',
    is_vegetarian: true,
    serving_size: '1 bowl (150g)',
    serving_grams: 150,
    calories: 100,
    protein_g: 3,
    carbs_g: 10,
    fat_g: 6,
    fiber_g: 3,
    source: 'ifct-approximate',
  },
  {
    id: 'baingan-bharta',
    name: 'Baingan Bharta',
    aliases: ['roasted eggplant', 'brinjal bharta'],
    category: 'sabzi',
    is_vegetarian: true,
    serving_size: '1 bowl (150g)',
    serving_grams: 150,
    calories: 110,
    protein_g: 3,
    carbs_g: 12,
    fat_g: 6,
    fiber_g: 4,
    source: 'ifct-approximate',
  },
  {
    id: 'matar-paneer',
    name: 'Matar Paneer',
    aliases: ['peas paneer'],
    category: 'sabzi',
    is_vegetarian: true,
    serving_size: '1 bowl (150g)',
    serving_grams: 150,
    calories: 220,
    protein_g: 12,
    carbs_g: 14,
    fat_g: 13,
    fiber_g: 3,
    source: 'ifct-approximate',
  },
  {
    id: 'paneer-tikka',
    name: 'Paneer Tikka',
    aliases: ['grilled paneer', 'tandoori paneer'],
    category: 'sabzi',
    is_vegetarian: true,
    serving_size: '1 serving (150g)',
    serving_grams: 150,
    calories: 280,
    protein_g: 18,
    carbs_g: 8,
    fat_g: 20,
    fiber_g: 1,
    source: 'ifct-approximate',
  },
  {
    id: 'soya-chunks-curry',
    name: 'Soya Chunks Curry',
    aliases: ['meal maker curry', 'soya masala'],
    category: 'sabzi',
    is_vegetarian: true,
    serving_size: '1 bowl (150g)',
    serving_grams: 150,
    calories: 180,
    protein_g: 18,
    carbs_g: 14,
    fat_g: 5,
    fiber_g: 3,
    source: 'ifct-approximate',
  },

  // ─── ROTI / RICE ────────────────────────────────────────
  {
    id: 'wheat-roti',
    name: 'Whole Wheat Roti',
    aliases: ['chapati', 'phulka', 'roti'],
    category: 'roti_rice',
    is_vegetarian: true,
    serving_size: '1 roti',
    serving_grams: 35,
    calories: 80,
    protein_g: 3,
    carbs_g: 15,
    fat_g: 1,
    fiber_g: 2,
    source: 'ifct-approximate',
  },
  {
    id: 'rice',
    name: 'Rice',
    aliases: ['chawal', 'steamed rice', 'white rice'],
    category: 'roti_rice',
    is_vegetarian: true,
    serving_size: '1 katori (150g)',
    serving_grams: 150,
    calories: 180,
    protein_g: 3,
    carbs_g: 40,
    fat_g: 0.5,
    fiber_g: 0.5,
    source: 'ifct-approximate',
  },
  {
    id: 'plain-paratha',
    name: 'Paratha (plain)',
    aliases: ['parantha'],
    category: 'roti_rice',
    is_vegetarian: true,
    serving_size: '1 paratha',
    serving_grams: 50,
    calories: 150,
    protein_g: 4,
    carbs_g: 20,
    fat_g: 7,
    fiber_g: 2,
    source: 'ifct-approximate',
  },
  {
    id: 'multigrain-roti',
    name: 'Multigrain Roti',
    aliases: ['atta roti', 'multi atta chapati'],
    category: 'roti_rice',
    is_vegetarian: true,
    serving_size: '1 roti',
    serving_grams: 40,
    calories: 90,
    protein_g: 4,
    carbs_g: 15,
    fat_g: 2,
    fiber_g: 3,
    source: 'ifct-approximate',
  },

  // ─── EGGS / PROTEIN ─────────────────────────────────────
  {
    id: 'boiled-egg',
    name: 'Boiled Egg',
    aliases: ['anda', 'egg'],
    category: 'protein',
    is_vegetarian: false,
    serving_size: '1 egg',
    serving_grams: 50,
    calories: 70,
    protein_g: 6,
    carbs_g: 1,
    fat_g: 5,
    fiber_g: 0,
    source: 'ifct-approximate',
  },
  {
    id: 'egg-bhurji',
    name: 'Egg Bhurji',
    aliases: ['scrambled eggs', 'anda bhurji'],
    category: 'protein',
    is_vegetarian: false,
    serving_size: '2 eggs',
    serving_grams: 120,
    calories: 180,
    protein_g: 13,
    carbs_g: 3,
    fat_g: 13,
    fiber_g: 0,
    source: 'ifct-approximate',
  },
  {
    id: 'paneer-raw',
    name: 'Paneer (raw)',
    aliases: ['cottage cheese', 'paneer'],
    category: 'protein',
    is_vegetarian: true,
    serving_size: '100g',
    serving_grams: 100,
    calories: 265,
    protein_g: 18,
    carbs_g: 4,
    fat_g: 20,
    fiber_g: 0,
    source: 'ifct-approximate',
  },
  {
    id: 'greek-yogurt',
    name: 'Greek Yogurt',
    aliases: ['hung curd', 'strained yogurt'],
    category: 'protein',
    is_vegetarian: true,
    serving_size: '100g',
    serving_grams: 100,
    calories: 60,
    protein_g: 10,
    carbs_g: 4,
    fat_g: 0.5,
    fiber_g: 0,
    source: 'ifct-approximate',
  },
  {
    id: 'curd-dahi',
    name: 'Curd / Dahi',
    aliases: ['yogurt', 'dahi'],
    category: 'protein',
    is_vegetarian: true,
    serving_size: '1 katori',
    serving_grams: 100,
    calories: 60,
    protein_g: 3,
    carbs_g: 5,
    fat_g: 3,
    fiber_g: 0,
    source: 'ifct-approximate',
  },
  {
    id: 'whey-protein',
    name: 'Whey Protein',
    aliases: ['protein shake', 'whey'],
    category: 'protein',
    is_vegetarian: true,
    serving_size: '1 scoop (30g)',
    serving_grams: 30,
    calories: 120,
    protein_g: 24,
    carbs_g: 3,
    fat_g: 1,
    fiber_g: 0,
    source: 'ifct-approximate',
  },
  {
    id: 'soya-chunks-dry',
    name: 'Soya Chunks (dry)',
    aliases: ['meal maker', 'soy nuggets', 'nutrela'],
    category: 'protein',
    is_vegetarian: true,
    serving_size: '50g dry',
    serving_grams: 50,
    calories: 170,
    protein_g: 26,
    carbs_g: 16,
    fat_g: 0.5,
    fiber_g: 7,
    source: 'ifct-approximate',
  },

  // ─── BREAKFAST ──────────────────────────────────────────
  {
    id: 'poha',
    name: 'Poha',
    aliases: ['flattened rice', 'chivda'],
    category: 'breakfast',
    is_vegetarian: true,
    serving_size: '1 plate',
    serving_grams: 200,
    calories: 180,
    protein_g: 4,
    carbs_g: 30,
    fat_g: 5,
    fiber_g: 2,
    source: 'ifct-approximate',
  },
  {
    id: 'upma',
    name: 'Upma',
    aliases: ['suji upma', 'rava upma'],
    category: 'breakfast',
    is_vegetarian: true,
    serving_size: '1 plate',
    serving_grams: 200,
    calories: 200,
    protein_g: 5,
    carbs_g: 28,
    fat_g: 8,
    fiber_g: 2,
    source: 'ifct-approximate',
  },
  {
    id: 'moong-dal-cheela',
    name: 'Moong Dal Cheela',
    aliases: ['moong chilla', 'dal cheela'],
    category: 'breakfast',
    is_vegetarian: true,
    serving_size: '2 pieces',
    serving_grams: 150,
    calories: 160,
    protein_g: 10,
    carbs_g: 20,
    fat_g: 4,
    fiber_g: 3,
    source: 'ifct-approximate',
  },
  {
    id: 'idli',
    name: 'Idli',
    aliases: ['steamed idli'],
    category: 'breakfast',
    is_vegetarian: true,
    serving_size: '2 pieces',
    serving_grams: 120,
    calories: 140,
    protein_g: 4,
    carbs_g: 28,
    fat_g: 1,
    fiber_g: 1,
    source: 'ifct-approximate',
  },
  {
    id: 'besan-cheela',
    name: 'Besan Cheela',
    aliases: ['gram flour pancake', 'besan chilla'],
    category: 'breakfast',
    is_vegetarian: true,
    serving_size: '2 pieces',
    serving_grams: 150,
    calories: 200,
    protein_g: 12,
    carbs_g: 22,
    fat_g: 7,
    fiber_g: 4,
    source: 'ifct-approximate',
  },
  {
    id: 'oats-milk',
    name: 'Oats with Milk',
    aliases: ['oatmeal', 'porridge'],
    category: 'breakfast',
    is_vegetarian: true,
    serving_size: '1 bowl',
    serving_grams: 250,
    calories: 220,
    protein_g: 10,
    carbs_g: 32,
    fat_g: 5,
    fiber_g: 4,
    source: 'ifct-approximate',
  },

  // ─── FRUITS / SNACKS ───────────────────────────────────
  {
    id: 'banana',
    name: 'Banana',
    aliases: ['kela'],
    category: 'fruits_snacks',
    is_vegetarian: true,
    serving_size: '1 medium',
    serving_grams: 120,
    calories: 105,
    protein_g: 1,
    carbs_g: 27,
    fat_g: 0.4,
    fiber_g: 3,
    source: 'ifct-approximate',
  },
  {
    id: 'apple',
    name: 'Apple',
    aliases: ['seb'],
    category: 'fruits_snacks',
    is_vegetarian: true,
    serving_size: '1 medium',
    serving_grams: 180,
    calories: 80,
    protein_g: 0.5,
    carbs_g: 21,
    fat_g: 0.3,
    fiber_g: 4,
    source: 'ifct-approximate',
  },
  {
    id: 'makhana',
    name: 'Makhana',
    aliases: ['fox nuts', 'lotus seeds'],
    category: 'fruits_snacks',
    is_vegetarian: true,
    serving_size: '30g',
    serving_grams: 30,
    calories: 110,
    protein_g: 3,
    carbs_g: 20,
    fat_g: 0.7,
    fiber_g: 1,
    source: 'ifct-approximate',
  },
  {
    id: 'mixed-nuts',
    name: 'Mixed Nuts',
    aliases: ['dry fruits', 'trail mix', 'nuts'],
    category: 'fruits_snacks',
    is_vegetarian: true,
    serving_size: '30g',
    serving_grams: 30,
    calories: 180,
    protein_g: 5,
    carbs_g: 7,
    fat_g: 16,
    fiber_g: 2,
    source: 'ifct-approximate',
  },
  {
    id: 'peanut-butter',
    name: 'Peanut Butter',
    aliases: ['pb'],
    category: 'fruits_snacks',
    is_vegetarian: true,
    serving_size: '1 tbsp (16g)',
    serving_grams: 16,
    calories: 95,
    protein_g: 4,
    carbs_g: 3,
    fat_g: 8,
    fiber_g: 1,
    source: 'ifct-approximate',
  },

  // ─── DRINKS ─────────────────────────────────────────────
  {
    id: 'milk',
    name: 'Milk',
    aliases: ['doodh', 'full cream milk'],
    category: 'drinks',
    is_vegetarian: true,
    serving_size: '200ml',
    serving_grams: 200,
    calories: 120,
    protein_g: 6,
    carbs_g: 10,
    fat_g: 6,
    fiber_g: 0,
    source: 'ifct-approximate',
  },
  {
    id: 'chaas',
    name: 'Chaas / Buttermilk',
    aliases: ['buttermilk', 'mattha', 'lassi'],
    category: 'drinks',
    is_vegetarian: true,
    serving_size: '200ml',
    serving_grams: 200,
    calories: 40,
    protein_g: 2,
    carbs_g: 5,
    fat_g: 1,
    fiber_g: 0,
    source: 'ifct-approximate',
  },
  {
    id: 'black-coffee',
    name: 'Black Coffee',
    aliases: ['coffee', 'espresso'],
    category: 'drinks',
    is_vegetarian: true,
    serving_size: '1 cup',
    serving_grams: 200,
    calories: 5,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 0,
    fiber_g: 0,
    source: 'ifct-approximate',
  },
  {
    id: 'tea-with-milk',
    name: 'Tea with Milk',
    aliases: ['chai', 'masala chai'],
    category: 'drinks',
    is_vegetarian: true,
    serving_size: '1 cup',
    serving_grams: 150,
    calories: 30,
    protein_g: 1,
    carbs_g: 4,
    fat_g: 1,
    fiber_g: 0,
    source: 'ifct-approximate',
  },
]

export const FOOD_MAP = new Map<string, Food>(FOODS.map((f) => [f.id, f]))

export function searchFoods(query: string): Food[] {
  const q = query.toLowerCase().trim()
  if (!q) return FOODS
  return FOODS.filter(
    (f) =>
      f.name.toLowerCase().includes(q) ||
      f.aliases.some((a) => a.toLowerCase().includes(q)),
  )
}

export function getFoodsByCategory(category: FoodCategory): Food[] {
  return FOODS.filter((f) => f.category === category)
}

export const FOOD_CATEGORIES: { id: FoodCategory; label: string }[] = [
  { id: 'dal', label: 'Dal' },
  { id: 'sabzi', label: 'Sabzi' },
  { id: 'roti_rice', label: 'Roti/Rice' },
  { id: 'protein', label: 'Protein' },
  { id: 'breakfast', label: 'Breakfast' },
  { id: 'fruits_snacks', label: 'Fruits/Snacks' },
  { id: 'drinks', label: 'Drinks' },
]
