-- 041_food_data.sql
-- F1 — Food data foundations: portion conversions, alias table, a shared
-- AI-estimate fallback table, and pg_trgm fuzzy-match indexes. The bulk IFCT
-- 2017 ingredient rows are loaded SEPARATELY via supabase/seed-food-ifct.sql
-- (generated by scripts/seed-food.ts) so this migration stays small and readable.
--
-- RUN THIS FILE WHOLE in the Supabase SQL editor (paste + Run).
--
-- ─────────────────────────────────────────────────────────────────────────────
-- NAMING NOTE: the batch spec called the shared-global fallback table
-- "custom_foods", but that name is already taken — migration 015 created a
-- PER-USER custom_foods table (recipes: uuid pk, user_id, RLS-by-owner) that
-- recipe_ingredients and meal_logs.custom_food_id already reference. Repurposing
-- it would break the existing recipes feature. The new shared-global table is
-- named `ai_food_estimates` instead; F2 (parse-meal) resolves against
-- food_library + food_aliases + ai_food_estimates, in that order.
--
-- FOOD ID SCHEME  (food_library.id is TEXT; three non-overlapping ranges)
--   Range 1 — IFCT 2017 ingredients   : id = the official IFCT food code,
--                                        e.g. 'A001'..'T###' (UPPERCASE letter +
--                                        digits). source = 'ifct'. Loaded by
--                                        seed-food-ifct.sql.
--   Range 2 — Composite / prepared dishes : id = lowercase-kebab slug, e.g.
--                                        'toor-dal', 'palak-paneer'. source =
--                                        'ifct'/'manual'. Hand-authored; the rows
--                                        seeded by seed-foods.sql already live here.
--   Range 3 — ai_food_estimates (SEPARATE TABLE) : its own bigint identity
--                                        sequence starting at 1. NEVER written
--                                        into food_library. NO user_id
--                                        (shared-global).
--   The three ranges are lexically disjoint (UPPERCASE codes vs kebab slugs vs a
--   distinct table), so a resolver can never confuse an IFCT ingredient, a
--   composite dish, and an AI-estimated fallback food.
-- ─────────────────────────────────────────────────────────────────────────────
--
-- ROLLBACK:
--   drop table if exists ai_food_estimates;
--   drop table if exists food_aliases;
--   drop table if exists portion_conversions;
--   drop index if exists food_library_name_trgm;
--   -- pg_trgm left installed (harmless).

-- Fuzzy text matching for the meal parser (trigram similarity + GIN indexes).
create extension if not exists pg_trgm;

-- ── portion_conversions ──────────────────────────────────────────────────────
-- Maps a household unit (katori, plate, piece, glass…) to grams for a given food.
create table if not exists portion_conversions (
  food_id          text    not null references food_library(id) on delete cascade,
  unit             text    not null,
  grams_equivalent numeric not null check (grams_equivalent > 0),
  primary key (food_id, unit)
);

alter table portion_conversions enable row level security;
create policy "Authenticated can read portions"
  on portion_conversions for select to authenticated using (true);
-- Writes are service-role only (no write policy).

-- ── food_aliases ─────────────────────────────────────────────────────────────
-- Alternate spellings / names → a food_library id. Complements the inline
-- food_library.aliases[] column and is the trigram search target for the parser.
create table if not exists food_aliases (
  id         bigint generated always as identity primary key,
  alias_text text   not null,
  food_id    text   not null references food_library(id) on delete cascade,
  unique (alias_text, food_id)
);

alter table food_aliases enable row level security;
create policy "Authenticated can read aliases"
  on food_aliases for select to authenticated using (true);
-- Writes are service-role only (no write policy).

create index if not exists food_aliases_food_id_idx on food_aliases (food_id);

-- ── ai_food_estimates (SHARED-GLOBAL — NO user_id) ───────────────────────────
-- Foods the parser could not resolve against the library, added once and shared
-- by every profile. normalized_name is the dedup key (lowercased, trimmed).
-- Named separately from the pre-existing per-user `custom_foods` (recipes)
-- table — see the NAMING NOTE at the top of this file.
create table if not exists ai_food_estimates (
  id              bigint generated always as identity primary key,
  normalized_name text    not null unique,
  name            text    not null,
  calories        numeric not null,          -- per serving_grams
  protein_g       numeric not null,
  carbs_g         numeric not null,
  fat_g           numeric not null,
  fiber_g         numeric not null default 0,
  serving_size    text    not null default '100 g',
  serving_grams   numeric not null default 100,
  source          text    not null default 'custom'
                    check (source in ('custom', 'ai_estimated')),
  created_at      timestamptz not null default now()
);

alter table ai_food_estimates enable row level security;
create policy "Authenticated can read ai food estimates"
  on ai_food_estimates for select to authenticated using (true);
-- Shared-global: any authenticated user (incl. the parse-meal edge function,
-- which calls the DB as an authenticated user) may contribute a new estimate.
-- Dedup is enforced by the normalized_name UNIQUE constraint.
create policy "Authenticated can add ai food estimates"
  on ai_food_estimates for insert to authenticated with check (true);

-- ── trigram indexes ──────────────────────────────────────────────────────────
create index if not exists food_library_name_trgm
  on food_library using gin (name gin_trgm_ops);
create index if not exists food_aliases_alias_trgm
  on food_aliases using gin (alias_text gin_trgm_ops);
create index if not exists ai_food_estimates_norm_trgm
  on ai_food_estimates using gin (normalized_name gin_trgm_ops);

-- ── minimal portion set (~30 foods the two users actually eat) ───────────────
-- FK-safe + idempotent: only inserts a portion whose food already exists, and
-- re-runs are no-ops via ON CONFLICT.
insert into portion_conversions (food_id, unit, grams_equivalent)
select v.food_id, v.unit, v.grams
from (values
  -- Dals (cooked) — katori / small_katori / plate(=big bowl)
  ('toor-dal','katori',150),   ('toor-dal','small_katori',100),   ('toor-dal','plate',200),
  ('moong-dal','katori',150),  ('moong-dal','small_katori',100),  ('moong-dal','plate',200),
  ('chana-dal','katori',150),  ('chana-dal','small_katori',100),  ('chana-dal','plate',200),
  ('masoor-dal','katori',150), ('masoor-dal','small_katori',100), ('masoor-dal','plate',200),
  ('rajma','katori',150),      ('rajma','small_katori',100),      ('rajma','plate',200),
  ('chole','katori',150),      ('chole','small_katori',100),      ('chole','plate',200),
  ('dal-makhani','katori',150),('dal-makhani','small_katori',100),('dal-makhani','plate',200),
  -- Rice
  ('rice','katori',150), ('rice','small_katori',100), ('rice','plate',300),
  -- Rotis / parathas (piece)
  ('wheat-roti','piece',35), ('multigrain-roti','piece',40), ('plain-paratha','piece',50),
  -- Sabzi
  ('aloo-gobi','katori',150),        ('aloo-gobi','small_katori',100),        ('aloo-gobi','plate',200),
  ('palak-paneer','katori',150),     ('palak-paneer','small_katori',100),     ('palak-paneer','plate',200),
  ('paneer-bhurji','katori',150),    ('paneer-bhurji','small_katori',100),    ('paneer-bhurji','plate',200),
  ('mixed-veg-sabzi','katori',150),  ('mixed-veg-sabzi','small_katori',100),  ('mixed-veg-sabzi','plate',200),
  ('bhindi-masala','katori',150),    ('bhindi-masala','small_katori',100),    ('bhindi-masala','plate',200),
  ('baingan-bharta','katori',150),   ('baingan-bharta','small_katori',100),   ('baingan-bharta','plate',200),
  ('matar-paneer','katori',150),     ('matar-paneer','small_katori',100),     ('matar-paneer','plate',200),
  ('soya-chunks-curry','katori',150),('soya-chunks-curry','small_katori',100),('soya-chunks-curry','plate',200),
  ('paneer-tikka','plate',150),      ('paneer-tikka','piece',25),
  -- Dairy / high-protein
  ('curd-dahi','katori',100),  ('curd-dahi','small_katori',60),  ('curd-dahi','glass',200),
  ('greek-yogurt','katori',100), ('greek-yogurt','small_katori',60),
  ('paneer-raw','piece',25),   ('paneer-raw','katori',100),
  ('milk','glass',200),        ('milk','small_katori',100),
  ('chaas','glass',200),
  -- Eggs
  ('boiled-egg','piece',50),   ('egg-bhurji','plate',120),
  -- Breakfast
  ('poha','plate',200),        ('poha','katori',150),
  ('upma','plate',200),        ('upma','katori',150),
  ('idli','piece',60),         ('idli','plate',120),
  ('oats-milk','katori',250),
  ('besan-cheela','piece',60), ('besan-cheela','plate',120),
  ('moong-dal-cheela','piece',60), ('moong-dal-cheela','plate',120),
  -- Fruit / snacks / drinks
  ('banana','piece',120),      ('apple','piece',180),
  ('makhana','katori',25),
  ('tea-with-milk','glass',150)
) as v(food_id, unit, grams)
where exists (select 1 from food_library f where f.id = v.food_id)
on conflict (food_id, unit) do nothing;

-- ── common spelling aliases ──────────────────────────────────────────────────
insert into food_aliases (alias_text, food_id)
select v.alias_text, v.food_id
from (values
  ('dal','toor-dal'), ('daal','toor-dal'), ('dhal','toor-dal'), ('arhar','toor-dal'), ('arhar dal','toor-dal'),
  ('moong','moong-dal'), ('mung','moong-dal'), ('mung dal','moong-dal'), ('moong daal','moong-dal'),
  ('masoor','masoor-dal'), ('chana','chana-dal'),
  ('chole','chole'), ('chhole','chole'), ('chholay','chole'), ('chana masala','chole'),
  ('rajmah','rajma'), ('rajma masala','rajma'),
  ('chawal','rice'), ('bhat','rice'), ('steamed rice','rice'),
  ('roti','wheat-roti'), ('chapati','wheat-roti'), ('chapathi','wheat-roti'), ('phulka','wheat-roti'),
  ('anda','boiled-egg'), ('egg','boiled-egg'),
  ('dahi','curd-dahi'), ('curd','curd-dahi'), ('yoghurt','curd-dahi'),
  ('doodh','milk'), ('paneer','paneer-raw'),
  ('chai','tea-with-milk'), ('buttermilk','chaas'), ('mattha','chaas')
) as v(alias_text, food_id)
where exists (select 1 from food_library f where f.id = v.food_id)
on conflict (alias_text, food_id) do nothing;
